FROM node:20 as build

WORKDIR /app

COPY package*.json ./
COPY nx.json tsconfig.base.json jest.preset.js ./
RUN npm install

# Copy source code
COPY . .

# Build frontend only
RUN npx nx build frontend

# Serve using Nginx
FROM nginx:alpine
COPY dist/frontend/browser/ /usr/share/nginx/html/
